### ISSUE TITLE
KeyError: 'Note'

### ISSUE THREAD

**Issue by lhmngwy** [chernals/swissborg_to_coinstats#4]
Hello,

Seems like swissborg may have made changes to their xlsx format since this script was written, currently getting the following errors:

> lee@lee:~/Downloads/swissborg_to_coinstats$ python3 sb2cs.py account_statement.xlsx swissborg.csv
> Traceback (most recent call last):
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'Note'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "sb2cs.py", line 74, in <module>
>     convert(SOURCE_FILE, sys.argv[2])
>   File "sb2cs.py", line 56, in convert
>     sb['Price'] = sb.apply(calculate_price, axis=1)
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 8839, in apply
>     return op.apply().__finalize__(self, method="apply")
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 727, in apply
>     return self.apply_standard()
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 851, in apply_standard
>     results, res_index = self.apply_series_generator()
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 867, in apply_series_generator
>     results[i] = self.f(v)
>   File "sb2cs.py", line 37, in calculate_price
>     value = find_exchange_pair(row['Note'])[0]
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/series.py", line 958, in __getitem__
>     return self._get_value(key)
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/series.py", line 1069, in _get_value
>     loc = self.index.get_loc(label)
>   File "/home/lee/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
>     raise KeyError(key) from err
> KeyError: 'Note'

I've attached a minimal xlsx file which can reproduce this.

Cheers!

[account_statement.xlsx](https://github.com/chernals/swissborg_to_coinstats/files/8420158/account_statement.xlsx)

**Comment by chernals** [comment]
Thanks for providing this, I'll try to find some time to work on it. Are you interested in a fix to make it work quickly or have you found another way?

**Comment by lhmngwy** [comment]
Cheers, no rush from me but would be nice to have it working.

I copied and pasted the new format into the old format to try to work around it, but then I ran into another problem. All of the fees in the CSV are in USD, but when I import into coinstats it thinks that the fees are in the currency of the crypto that I'm buying or selling. As a result, coinstats thinks that I have -52.11 ETH because of fees which were actually $52.11.

I've attached the full xlsx file I used and the csv that was generate from it.

[example_account_statement.xlsx](https://github.com/chernals/swissborg_to_coinstats/files/8496983/example_account_statement.xlsx)
[example_account_statement.csv](https://github.com/chernals/swissborg_to_coinstats/files/8496982/example_account_statement.csv)

**Comment by chernals** [comment]
Thanks for providing a reroducible example. I'll make sure it all works fine again.

The issue with the fees is not directly due to my script, I had to make choices and at the time I remember that I realized that the CoinStats api (csv columns) is very poor (as for many other things in terms of portfolio management).

In the meantime, let's spread the word and upvote the feature request : https://feedback.coinstats.app/b/feature-requests/swissborg-wallet-connection .
